name: temos
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.2.25=hca03da5_0
  - expat=2.7.1=h313beb8_0
  - libcxx=17.0.6=he5c5206_4
  - libffi=3.4.4=hca03da5_1
  - ncurses=6.5=hee39554_0
  - openssl=3.0.17=h4ee41c1_0
  - pip=25.1=pyhc872135_2
  - python=3.9.23=h99c0cbc_0
  - readline=8.2=h1a28f6b_0
  - setuptools=78.1.1=py39hca03da5_0
  - sqlite=3.50.2=h79febb2_1
  - tk=8.6.14=h6ba3021_1
  - wheel=0.45.1=py39hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - antlr4-python3-runtime==4.9.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - certifi==2025.7.14
      - charset-normalizer==3.4.2
      - chumpy==0.70
      - colorlog==6.9.0
      - einops==0.8.1
      - filelock==3.18.0
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - gdown==5.2.0
      - hf-xet==1.1.5
      - huggingface-hub==0.34.3
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - idna==3.10
      - jinja2==3.1.6
      - lightning-utilities==0.15.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.6.3
      - networkx==3.2.1
      - numpy==1.23.5
      - omegaconf==2.3.0
      - packaging==25.0
      - pandas==2.3.1
      - pillow==11.3.0
      - propcache==0.3.2
      - psutil==7.0.0
      - pydeprecate==0.3.2
      - pygments==2.19.2
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==1.9.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - regex==2025.7.34
      - requests==2.32.4
      - rich==14.1.0
      - safetensors==0.5.3
      - scipy==1.13.1
      - shortuuid==1.0.13
      - six==1.17.0
      - smplx==0.1.28
      - soupsieve==2.7
      - sympy==1.14.0
      - tokenizers==0.21.4
      - torch==1.10.0
      - torchaudio==0.10.1
      - torchmetrics==0.7.0
      - torchvision==0.11.2
      - tqdm==4.67.1
      - transformers==4.49.0
      - typing-extensions==4.14.1
      - tzdata==2025.2
      - urllib3==2.5.0
      - yarl==1.20.1
prefix: /Users/lawrence/miniconda3/envs/temos
